import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'react-hot-toast'
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/components/AuthProvider";

export const metadata: Metadata = {
  title: "Blonify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-prime">
        <AuthProvider>
          <Navbar />
        {children}
        <Toaster position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
