import mongoose from "mongoose";

const postSchema = new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    coverImg:{
        type:String,
    },
    title:{
        type:String,
        required:true,
    },
    slug:{
        type:String,
        required:true,
        unique:true
    },
    altText:{
        type:String,
    },
    desc:{
        type:String,
    },
    category:{
        type:String,
        default:"uncategorized",
    },
    content:{
        type:String,
        required:true,
    },
    isFeatured:{
        type:String,
        default:"false",
    },
    visits:{
        type:Number,
        default:0,
    },
    highlight:{
        type:String
    },
    network:[
        {
            technology:{
                type:String
            },
            towbands:{
                type:String
            },
            threebands:{
                type:String
            },
            fourbands:{
                type:String
            },
            fivebands:{
                type:String
            },
            speed:{
                type:String
            }
        }
    ],
    launch:[
        {
            date:{
                type:String
            },
            status:{
                type:String
            }
        }
    ],
    body:[
        {
            dimensions:{
                type:String
            },
            weight:{
                type:String
            },
            build:{
                type:String
            },
            sim:{
                type:String
            }
        }
    ],
    display:[
        {
            type:{
                type:String
            },
            resolution:{
                type:String
            },
            size:{
                type:String
            },
            refreshrate:{
                type:String
            },
            protection:{
                type:String
            },
            pixle:{
                type:String
            },
            big:{
                type:String
            }
        }
    ],
    platform:[
        {
            os:{
                type:String
            },
            chipset:{
                type:String
            },
            gpu:{
                type:String
            },
            cpu:{
                type:String
            },
            process:{
                type:String
            },
            ram:{
                type:String
            }

        }
    ],
    memory:[
        {
            cardslot:{
                type:String
            },
            ram:{
                type:String
            },
            storage:{
                type:String
            }
        }
    ],
    permormance:[
        {
            antutuscore:{
                type:String
            },
            geeksbenchscore:{
                type:String
            },

            pubgfps:{
                type:String
            },
            freefirefps:{
                type:String
            },
            callofdutyfps:{
                type:String
            }
        }
    ],
    battery:[
        {
            type:{
                type:String
            },
            capacity:{
                type:String
            },
            fastcharge:{
                type:String
            },
            gamingbackup:{
                type:String
            },
            standbybackup:{
                type:String
            },
            mah:{
                type:String
            },
            wiredcharge:{
                type:String
            },
            wirelesscharge:{
                type:String
            }
        }
    ],
    maincam:[
        {
            type:{
                type:String
            },
            mp:{
                type:String
            },
            resolution:{
                type:String
            },
            zoom:{
                type:String
            },
            features:{
                type:String
            },
            videofps:{
                type:String
            },
            mega:{
                type:String
            },
            pixel:{
                type:String
            }
        }
    ],
    frontcam:[
        {
            type:{
                type:String
            },
            mp:{
                type:String
            },
            resolution:{
                type:String
            },
            features:{
                type:String
            },
            videofps:{
                type:String
            }
        }
    ],
    sound:[
        {
            speaker:{
                type:String
            },
            headphonejack:{
                type:String
            },
            quality:{
                type:String
            }
        }
    ],
    comms:[
        {
            wifi:{
                type:String
            },
            bluetooth:{
                type:String
            },
            gps:{
                type:String
            },
            nfc:{
                type:String
            }
        }
    ],
    features:[
        {
            sensor:{
                type:String
            },
            fingerprint:{
                type:String
            },
            faceunlock:{
                type:String
            },
            ir:{
                type:String
            }
        }
    ],
    mics:[
        {
            color:{
                type:String
            },
            quality:{
                type:String
            },
            model:{
                type:String
            },
            price:{
                type:String
            }
        }
    ],
    ismobile:{
        type:String,
        default:"false"
    },
    islaptop:{
        type:String,
        default:"false"
    },
    iswatch:{
        type:String,
        default:"false"
    },

},{timestamps:true});

export default mongoose.model("Post",postSchema);